# Generated by Django 5.0.3 on 2026-02-18 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('READING', 'Reading'), ('LISTENING', 'Listening'), ('SPEAKING', 'Speaking'), ('WRITING', 'Writing'), ('GRAMMAR', 'Grammar'), ('VOCABULARY', 'Vocabulary')], max_length=20)),
                ('level', models.CharField(choices=[('A1', 'A1 Beginner'), ('A2', 'A2 Pre-Intermediate'), ('B1', 'B1 Intermediate'), ('B2', 'B2 Upper Intermediate'), ('C1', 'C1 Advanced')], max_length=2)),
                ('order', models.IntegerField(default=0)),
                ('content_json', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'A1 Beginner'), ('A2', 'A2 Pre-Intermediate'), ('B1', 'B1 Intermediate'), ('B2', 'B2 Upper Intermediate'), ('C1', 'C1 Advanced')], default='A1', max_length=2)),
                ('progress_reading', models.IntegerField(default=0)),
                ('progress_listening', models.IntegerField(default=0)),
                ('progress_speaking', models.IntegerField(default=0)),
                ('progress_writing', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('total_time_hours', models.IntegerField(default=0)),
                ('profile_picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
