# Generated by Django 5.0.3 on 2026-02-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('READING', 'Reading'), ('LISTENING', 'Listening'), ('SPEAKING', 'Speaking'), ('WRITING', 'Writing'), ('GRAMMAR', 'Grammar'), ('VOCABULARY', 'Vocabulary'), ('QUIZ', 'Quiz')], max_length=20),
        ),
    ]
