# Generated by Django 5.0.3 on 2026-02-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_completed_placement_test',
            field=models.BooleanField(default=False),
        ),
    ]
