# Generated by Django 5.0.3 on 2026-02-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_has_completed_placement_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('A1', 'A1 Beginner'), ('A2', 'A2 Basic'), ('B1', 'B1 Intermediate'), ('B2', 'B2 Upper Intermediate'), ('C1', 'C1 Advanced')], max_length=2)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='level',
            field=models.CharField(choices=[('A1', 'A1 Beginner'), ('A2', 'A2 Basic'), ('B1', 'B1 Intermediate'), ('B2', 'B2 Upper Intermediate'), ('C1', 'C1 Advanced')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('A1', 'A1 Beginner'), ('A2', 'A2 Basic'), ('B1', 'B1 Intermediate'), ('B2', 'B2 Upper Intermediate'), ('C1', 'C1 Advanced')], default='A1', max_length=2),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.topic'),
        ),
    ]
