#!/usr/bin/env bash
# exit on error
set -o errexit

pip install -r requirements.txt
python manage.py migrate

# Populate database with initial content
python populate_database.py

# Collect static files (including any generated by the scripts)
python manage.py collectstatic --no-input
